#!/usr/bin/python
import re
user_file_dir = input(r"Enter the file dir : ") # escaping
with open(user_file_dir, 'r') as Mush_file: # opening the file reading it.
    for catch_lines in Mush_file: # loop to look over finding the password
        if 'password=' in catch_lines: # finding 
          print("We found it. You should encrypt your passwords .. ") # seems we got
     
print ("\nThe app is done working .. CU") # terminat the app

