#!/usr/bin/env python3
from wsgiref.simple_server import make_server
import sqlite3
def get_form_vals(post_str):
	form_vals = {item.split("=")[0]: item.split("=")[1] for item in post_str.decode().split("&")}
	return form_vals

def hello_world_app(environ, start_response):
	filename = 'C:\sqlite\HW9_DB.db' # it's my database to store our animals in.
	conn = sqlite3.connect(filename) # get connection
	message=""
	status = '200 OK'
	headers = [('Content-type', 'html; charset=utf-8')]
	start_response(status, headers)
	if(environ['REQUEST_METHOD'] == 'POST'):
		message += "<br>Your data has been recorded:"
		request_body_size = int(environ['CONTENT_LENGTH'])
		request_body = environ['wsgi.input'].read(request_body_size)
		form_vals = get_form_vals(request_body)
		list_s = {}
		list_s["count"] = ""
		list_s["Animal"] = ""
		for item in form_vals.keys():
			message += "<br/>"+item + " = " + form_vals[item]
			if(item == "animal"):
				list_s["Animal"] = form_vals[item]
			elif (item == "count"):
				list_s["count"] = form_vals[item]
		c = int(list_s["count"])
		query = "INSERT INTO Mush_tb (Animal_name, Count) VALUES ('%s',%i)" % (list_s["Animal"],c)
		conn.execute(query) 
		conn.commit()			

	message += "<h1>Welcome to the Zoo</h1>"
	message += "<form method='POST'><br>Animal:<input type=text name='animal'>"
	message += "<br><br>Count:<input type=text name='count'>"
	message += "<br><br><input type='submit' name='Submit' ></form>"
	return[bytes(message,'utf-8')]

httpd = make_server('', 8000, hello_world_app)
print("Serving on port 8000...")


httpd.serve_forever()
